# ReviewPro — validación independiente del Bloque 6 (conversiones y tamaños de efecto).
# Reimplementa en R cada conversión con qt()/qnorm() de R y escribe tests/r_reference_b6.js.
#   Uso: Rscript tools/validar_bloque6.R

library(jsonlite)
out <- list()

# DE desde EE, IC de la media (t con n − 1 gl) y CV
out$se <- list(se = 1.3, n = 9, sd = 1.3 * sqrt(9))
out$ci <- list(lo = 12.1, hi = 15.7, n = 8, sd = sqrt(8) * (15.7 - 12.1) / (2 * qt(0.975, 7)))
out$ci_big <- list(lo = 12.1, hi = 15.7, n = 80, sd = sqrt(80) * (15.7 - 12.1) / (2 * qnorm(0.975)))
out$cv <- list(cv = 18, mean = 6.2, sd = 0.18 * 6.2)

# DE común desde el ANOVA
out$lsd <- list(lsd = 0.85, r = 4, dfe = 12, alpha = 0.05, sd = 0.85 / (qt(0.975, 12) * sqrt(2 / 4)))
out$lsd10 <- list(lsd = 0.85, r = 3, dfe = 10, alpha = 0.10, sd = 0.85 / (qt(0.95, 10) * sqrt(2 / 3)))
out$sed <- list(sed = 0.42, r = 4, sd = 0.42 * sqrt(4 / 2))
out$sem <- list(sem = 0.30, r = 5, sd = 0.30 * sqrt(5))
out$cvexp <- list(cv = 12.5, grand = 7.4, sd = 12.5 / 100 * 7.4)
out$dfe <- list(crd = 5 * (4 - 1), rcbd = (5 - 1) * (4 - 1), latin = (5 - 1) * (5 - 2))

# Wan et al. (2014)
wanIQR <- function(q1, m, q3, n) c(mean = (q1 + m + q3) / 3, sd = (q3 - q1) / (2 * qnorm((0.75 * n - 0.125) / (n + 0.25))))
wanRange <- function(a, m, b, n) c(mean = (a + 2 * m + b) / 4, sd = (b - a) / (2 * qnorm((n - 0.375) / (n + 0.25))))
out$wan_iqr <- as.list(c(q1 = 4.1, m = 5.0, q3 = 6.3, n = 12, wanIQR(4.1, 5.0, 6.3, 12)))
out$wan_range <- as.list(c(a = 2.2, m = 5.0, b = 8.9, n = 12, wanRange(2.2, 5.0, 8.9, 12)))

# Estadísticos → d → g (Borenstein et al. 2009, cap. 4 y 7)
J <- function(m) exp(lgamma(m / 2) - 0.5 * log(m / 2) - lgamma((m - 1) / 2))
sp <- sqrt(((50 - 1) * 5.5^2 + (50 - 1) * 4.5^2) / 98)
d <- (103 - 100) / sp
g <- J(98) * d
out$borenstein <- list(d = d, J = J(98), g = g, vi = 1 / 50 + 1 / 50 + g^2 / (2 * 100), t = d / sqrt(1 / 50 + 1 / 50))
out$from_t <- list(t = 2.4, n1 = 10, n2 = 12, d = 2.4 * sqrt(1 / 10 + 1 / 12), g = J(20) * 2.4 * sqrt(1 / 10 + 1 / 12))
tp <- qt(1 - 0.031 / 2, 18)
out$from_p <- list(p = 0.031, n1 = 10, n2 = 10, d = tp * sqrt(1 / 10 + 1 / 10))
se <- (5.1 - 0.3) / (2 * qt(0.975, 30)); sdp <- se / sqrt(1 / 16 + 1 / 16)
out$from_ci <- list(lo = 0.3, hi = 5.1, diff = 2.7, n1 = 16, n2 = 16, se = se, sd = sdp, d = 2.7 / sdp)

# razón de respuesta con DE desde la DMS
sdl <- out$lsd$sd
out$rom_lsd <- list(m1 = 7.1, m2 = 6.2, n = 4, yi = log(7.1 / 6.2), vi = sdl^2 / (4 * 7.1^2) + sdl^2 / (4 * 6.2^2))

# CV medio para imputar
arms <- data.frame(mean = c(6, 7, 5, 8), sd = c(0.9, 1.4, NA, 1.2))
out$impute <- list(cv = mean(arms$sd / arms$mean, na.rm = TRUE))

writeLines(c("/* Generated by tools/validar_bloque6.R — do not edit by hand. */",
  paste0("window.RREF_B6 = ", toJSON(out, digits = NA, auto_unbox = TRUE), ";")), "tests/r_reference_b6.js")
cat("Borenstein: d", d, " g", g, " J", J(98), "\n")
cat("DMS → DE:", out$lsd$sd, "   Wan (RIC):", out$wan_iqr$mean, out$wan_iqr$sd, "\n")
