# ReviewPro — validación independiente del Bloque 4 (acuerdo y cota de verificación).
# Reimplementa en R, con tablas de contingencia y fórmulas escritas aparte:
#   * kappa de Cohen y su error estándar no nulo (Fleiss, Cohen y Everitt 1969);
#   * kappa de Fleiss (1971) sobre el ejemplo publicado de 14 evaluadores y 10 sujetos;
#   * la cota superior exacta de Clopper–Pearson con qbeta() de R.
# Escribe tests/r_reference_b4.js.   Uso: Rscript tools/validar_bloque4.R

library(jsonlite)
out <- list()

cohen <- function(a, b, cats) {
  tab <- table(factor(a, levels = cats), factor(b, levels = cats))
  n <- sum(tab); p <- tab / n
  r <- rowSums(p); c <- colSums(p)
  po <- sum(diag(p)); pe <- sum(r * c)
  k <- (po - pe) / (1 - pe)
  A <- sum(diag(p) * (1 - (r + c) * (1 - k))^2)
  B <- 0
  for (i in seq_along(cats)) for (j in seq_along(cats)) if (i != j) B <- B + p[i, j] * (c[i] + r[j])^2
  B <- B * (1 - k)^2
  C <- (k - pe * (1 - k))^2
  se <- sqrt(A + B - C) / ((1 - pe) * sqrt(n))
  list(kappa = k, po = po, pe = pe, se = se, n = n)
}

# ejemplo de libro: 50 sujetos, sí/sí 20, sí/no 5, no/sí 10, no/no 15 → kappa = 0.4
a <- c(rep("inc", 25), rep("exc", 25)); b <- c(rep("inc", 20), rep("exc", 5), rep("inc", 10), rep("exc", 15))
out$book <- c(cohen(a, b, c("inc", "exc")), list(a = a, b = b))

# tres categorías, 40 registros fijos
set.seed(4)
x <- sample(c("inc", "maybe", "exc"), 40, replace = TRUE, prob = c(.3, .1, .6))
y <- ifelse(runif(40) < .75, x, sample(c("inc", "maybe", "exc"), 40, replace = TRUE))
out$three <- c(cohen(x, y, c("inc", "maybe", "exc")), list(a = x, b = y))

# Fleiss (1971): ejemplo publicado (14 evaluadores, 10 sujetos, 5 categorías)
M <- matrix(c(0,0,0,0,14, 0,2,6,4,2, 0,0,3,5,6, 0,3,9,2,0, 2,2,8,1,1, 7,7,0,0,0, 3,2,6,3,0, 2,5,3,2,2, 6,5,2,1,0, 0,2,2,3,7), ncol = 5, byrow = TRUE)
N <- nrow(M); nr <- sum(M[1, ])
pj <- colSums(M) / (N * nr); Pi <- (rowSums(M^2) - nr) / (nr * (nr - 1))
Pbar <- mean(Pi); Pe <- sum(pj^2)
out$fleiss <- list(counts = M, kappa = (Pbar - Pe) / (1 - Pe), Pbar = Pbar, Pe = Pe)

# Clopper–Pearson unilateral al 95 %
cp <- data.frame(x = c(0, 0, 0, 1, 3), n = c(20, 50, 100, 50, 80))
cp$upper <- qbeta(0.95, cp$x + 1, cp$n - cp$x)
out$cp <- cp
out$samplesize <- list(share = c(0.05, 0.02, 0.01), n = ceiling(log(0.05) / log(1 - c(0.05, 0.02, 0.01))))

writeLines(c("/* Generated by tools/validar_bloque4.R — do not edit by hand. */",
  paste0("window.RREF_B4 = ", toJSON(out, digits = NA, auto_unbox = TRUE, dataframe = "rows"), ";")), "tests/r_reference_b4.js")
cat("libro: kappa", out$book$kappa, " se", out$book$se, "\n")
cat("tres categorías: kappa", out$three$kappa, " se", out$three$se, "\n")
cat("Fleiss: kappa", out$fleiss$kappa, " Pbar", Pbar, " Pe", Pe, "\n")
print(cp)
